# Generated by Django 6.0.2 on 2026-02-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_alert_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
